### ISSUE TITLE
Plugin does not work on Ubuntu

### ISSUE THREAD

**Issue by jdcaraujo** [roman-r-m/joplin-plugin-quick-links#11]
Hi @roman-r-m, first to all thank you so much for this plugin! I'm moving from Obsidian, and this is a feature I deeply missed in Joplin. 

I have two desktop apps of Joplin, one in a Windows machine and one in Ubuntu. On Windows, the plugin works perfectly, but on Ubuntu using the @@ doesn't trigger the dropdown at all. 

I checked the Joplin version (2.8.8) and removed all other plugins to check for any conflicts, but had no success. 

![Screenshot from 2022-07-03 16-59-31](https://user-images.githubusercontent.com/3432837/177047595-0c40297c-a77d-4d72-a1fb-579aa39506a1.png)

**Comment by roman-r-m** [comment]
Any errors in logs?

It works for me on Linux and I can't think of anything in this plugin that'd be OS dependent. Is your Joplin on Windows the same version as on Linux?

**Comment by jdcaraujo** [comment]
No errors on Logs, I turned the plugin off and on again, the only lines pertaining Quick Links is:

2022-07-03 21:31:40: joplin.plugins: "Starting plugin: com.whatever.quick-links"
2022-07-03 21:31:40: joplin.plugins: "Finished running onStart handler: com.whatever.quick-links (Took 806ms)"

When I try to use "@@", nothing appears in the logs. 

Also, checked the versions on Windows and Ubuntu, they're both 2.8.8..

Will try to re-install on Ubuntu.

**Comment by roman-r-m** [comment]
Stupid question, but the plugin is not disabled is it? I can't think of anything else without any clues in logs

**Comment by roman-r-m** [comment]
And can you also check the plugin version is the same on both systems

**Comment by jdcaraujo** [comment]
Yes, they're both in 1.2.3.. No problem, I'll keep updating and hopefully
the issue will go away. Keep up the great work!

**Comment by roman-r-m** [comment]
Ah, great, thanks for checking!
