### ISSUE TITLE
Joplin 2.14.6 not work

### ISSUE THREAD

**Issue by Dev-Wiki** [roman-r-m/joplin-plugin-quick-links#14]
Joplin 2.14.6 (prod, win32)

客户端 ID: a9d852d02a35472da7b5987090a2cde6
同步版本：3
配置文件版本：45
支持的密钥链：是

修订：92667ba

Copy Anchor Link: 1.1.0
Enhancement: 1.2.1
PlantUML2: 1.11.0
Quick Links: 1.2.4
Simple Backup: 1.3.5

**Comment by roman-r-m** [comment]
Are you using the rich text editor? It won't work there.

**Comment by Dev-Wiki** [comment]
![动画](https://github.com/roman-r-m/joplin-plugin-quick-links/assets/12946956/519be819-ce97-45ae-b694-51dc1cc06d67)


> Are you using the rich text editor? It won't work there.

markdown editor

**Comment by Dev-Wiki** [comment]
i download latest Release Version, it work as well

Joplin 2.13.13 (prod, win32)

客户端 ID: 106f0220dbc142999f0cc0b87fc0b87e
同步版本：3
配置文件版本：44
支持的密钥链：否

修订：c3cdeeb

Quick Links: 1.2.4

![image](https://github.com/roman-r-m/joplin-plugin-quick-links/assets/12946956/465a17e5-8b38-42fe-a61b-bebf5f47a3d2)

**Comment by Dev-Wiki** [comment]
I've identified the issue. If I check 'Opt-in to the editor beta', the plugin becomes disabled.

![image](https://github.com/roman-r-m/joplin-plugin-quick-links/assets/12946956/d8eab3c1-460d-49a2-8c1e-bf071828c9fd)

**Comment by Dev-Wiki** [comment]
> I've identified the issue. If I check 'Opt-in to the editor beta', the plugin becomes disabled.
> 
> ![image](https://private-user-images.githubusercontent.com/12946956/294856241-d8eab3c1-460d-49a2-8c1e-bf071828c9fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDYwNTksIm5iZiI6MTcwNDcwNTc1OSwicGF0aCI6Ii8xMjk0Njk1Ni8yOTQ4NTYyNDEtZDhlYWIzYzEtNDYwZC00OWEyLThjMWUtYmYwNzE4MjhjOWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5MjIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYTllYmM3MzNmNzc3OGQ0YTcxMzFjZjUzMjlhM2NlN2Q4M2IwYWJmYWViZjlhMGQ4YjBkN2FlM2RlYjMzYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ggQB2q72lBVSLPJ1CjRD1YLuAeyuddMmxoExhhsWBT8)

This option causes other plugins to become disabled as well.

**Comment by roman-r-m** [comment]
Ah, yes. This is because the beta editor is built with CodeMirror 6 which is completely different from version 5 which the plugin uses.
