### ISSUE TITLE
FR: works even in front of a closing bracket: e.g. @@)

### ISSUE THREAD

**Issue by janklostermann** [roman-r-m/joplin-plugin-quick-links#18]
This plugin is great! Thanks a lot!
Nonetheless I repeatedly run into a complication with it.

### Current situation
When I try to add a quick-link in a bracket, it just does not work, as it expects a white-space after the `@@`. 
This is surprisingly often, as Joplin's editor (thankfully) automatically adds the closing bracket with the opening one.
Example: 
```
some text (see also @@)
```

### Workaround
Introducing a white-space manually, and remove it afterwards again, makes it work, but feels like quite a lot additional unnecessary hussle. Especially if this situation occurs often. And it seems to be resolvable easily, but I might be wrong with that.
```
some text (see also @@ )
```

### Suggestion
If there could be some more symbols accepted as "white-space" in this situation, this would be great. (e.g. `)`, `]`, `}` )
Then you could directly continue writing `(see also )` -> `(see also @@otherNote)`.

Thanks for considering.

**Comment by roman-r-m** [comment]
What you suggesting makes sense.
In fact, it already works with CodeMirror 6 (enable "Opt-in to the editor beta" in settings). For CM5 I'll make the change now.

**Comment by roman-r-m** [comment]
Fixed in 1.3.2

**Comment by janklostermann** [comment]
Thanks so much! 
I will test as soon as 1.3.2 becomes available.
