### ISSUE TITLE
plugin not working?

### ISSUE THREAD

**Issue by cast-away** [roman-r-m/joplin-plugin-quick-links#2]
Hiya,

After installing your plugin (and restarting Joplin) no menu shows up when typing @@

Joplin version is 1.6.8 running on Kubuntu. Plugin was installed through Joplin itself.

I am sure I am missing something really obvious, apologies if I am just wasting your time.

Any

**Comment by roman-r-m** [comment]
The plugin needs Joplin 1.7+
There was a bug in Joplin that allowed installing a plugin regardless of the plugin's min version requirement.
