### ISSUE TITLE
Feature Request - When linking TODO notes, also show the checkbox

### ISSUE THREAD

**Issue by ZwodahS** [roman-r-m/joplin-plugin-quick-links#8]
This is similar to the embed search plugin https://discourse.joplinapp.org/t/embed-any-search-with-content/14328, would love to have the same here.

**Comment by roman-r-m** [comment]
If you mean in the viewer (i.e. on the right side) then it's out of scope for the plugin and has to be done in Joplin itself.

**Comment by ZwodahS** [comment]
Oh ya, that is right. Let me put that in the main joplin repo instead. Sorry for the trouble.
