### ISSUE TITLE
"@@" does not work in WYSIWYG editor

### ISSUE THREAD

**Issue by raffraffraff** [roman-r-m/joplin-plugin-quick-links#9]
When I type "@@" in the WYSIWYG editor, nothing happens. Perhaps it's not supposed to, but I can't find any mention of this limitation, and there don't appear to be any issues mentioning it either.

**Comment by roman-r-m** [comment]
Indeed it's not working and is not supposed to - none of the plugins that modify the editor do. (Some plugins like backup or note outline are editor-agnostic).
I'll add a note to the readme.
